site_name: Organization Documentation
site_url: ''
repo_url: ''
docs_dir: docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - navigation.indexes
  - search.suggest
  - search.highlight
  - content.code.copy
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
plugins:
- search
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tabbed
- admonition
- toc:
    permalink: true
nav:
- Home: index.md
- Repositories:
  - Oracle Alura Data Science Challenge 1:
    - Home: oracle-alura-data-science-challenge-1/index.md
    - Test Allura 1: oracle-alura-data-science-challenge-1/test-allura-1.md
